# Generated by Django 5.1.6 on 2026-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cooperadora_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='key_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
