# Generated by Django 5.1.6 on 2026-07-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_facturacion_electronica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='padre',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('rol', 'SOC'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to=settings.AUTH_USER_MODEL),
        ),
    ]
